"""initial domain schema

Revision ID: 31ea0922d2b7
Revises: 
Create Date: 2026-03-29 18:30:11.123342

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31ea0922d2b7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('concepts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('stocks',
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('region', sa.String(length=64), nullable=True),
    sa.Column('region_secondary', sa.String(length=64), nullable=True),
    sa.Column('industry', sa.String(length=128), nullable=True),
    sa.Column('industry_secondary', sa.String(length=128), nullable=True),
    sa.Column('industry_segment', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('themes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('narrative', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['themes.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_themes_parent_id'), 'themes', ['parent_id'], unique=False)
    op.create_index(op.f('ix_themes_slug'), 'themes', ['slug'], unique=False)
    op.create_table('stock_concepts',
    sa.Column('stock_code', sa.String(length=16), nullable=False),
    sa.Column('concept_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['stock_code'], ['stocks.code'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('stock_code', 'concept_id')
    )
    op.create_table('theme_stock_roles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('theme_id', sa.Integer(), nullable=False),
    sa.Column('stock_code', sa.String(length=16), nullable=False),
    sa.Column('role_name', sa.String(length=64), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['stock_code'], ['stocks.code'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['theme_id'], ['themes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('theme_id', 'stock_code', 'role_name', 'valid_from', name='uq_theme_stock_role_valid_from')
    )
    op.create_index(op.f('ix_theme_stock_roles_stock_code'), 'theme_stock_roles', ['stock_code'], unique=False)
    op.create_index(op.f('ix_theme_stock_roles_theme_id'), 'theme_stock_roles', ['theme_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_theme_stock_roles_theme_id'), table_name='theme_stock_roles')
    op.drop_index(op.f('ix_theme_stock_roles_stock_code'), table_name='theme_stock_roles')
    op.drop_table('theme_stock_roles')
    op.drop_table('stock_concepts')
    op.drop_index(op.f('ix_themes_slug'), table_name='themes')
    op.drop_index(op.f('ix_themes_parent_id'), table_name='themes')
    op.drop_table('themes')
    op.drop_table('stocks')
    op.drop_table('concepts')
    # ### end Alembic commands ###
